SEED_TRANSACTIONS = [
    ("Starbucks", 5.50, "FOOD_AND_DRINK"),
    ("McDonalds", 8.99, "FOOD_AND_DRINK"),
    ("Subway", 12.00, "FOOD_AND_DRINK"),
    ("Pizza Hut", 22.00, "FOOD_AND_DRINK"),
    ("Whole Foods", 87.00, "FOOD_AND_DRINK"),
    ("Uber", 14.50, "TRANSPORTATION"),
    ("Lyft", 18.00, "TRANSPORTATION"),
    ("Via Transportation", 6.00, "TRANSPORTATION"),
    ("TTC", 3.25, "TRANSPORTATION"),
    ("GO Transit", 12.00, "TRANSPORTATION"),
    ("Delta Airlines", 450.00, "TRAVEL"),
    ("United Airlines", 520.00, "TRAVEL"),
    ("Airbnb", 210.00, "TRAVEL"),
    ("Marriott Hotels", 189.00, "TRAVEL"),
    ("Expedia", 340.00, "TRAVEL"),
    ("Netflix", 15.99, "ENTERTAINMENT"),
    ("Spotify", 9.99, "ENTERTAINMENT"),
    ("Steam", 59.99, "ENTERTAINMENT"),
    ("AMC Theatres", 18.00, "ENTERTAINMENT"),
    ("Amazon Prime", 14.99, "ENTERTAINMENT"),
    ("Amazon", 45.00, "GENERAL_MERCHANDISE"),
    ("Walmart", 120.00, "GENERAL_MERCHANDISE"),
    ("Target", 67.00, "GENERAL_MERCHANDISE"),
    ("Best Buy", 299.00, "GENERAL_MERCHANDISE"),
    ("IKEA", 450.00, "GENERAL_MERCHANDISE"),
    ("Hydro One", 110.00, "RENT_AND_UTILITIES"),
    ("Rogers", 85.00, "RENT_AND_UTILITIES"),
    ("Bell Canada", 90.00, "RENT_AND_UTILITIES"),
    ("Enbridge Gas", 75.00, "RENT_AND_UTILITIES"),
    ("Rent Payment", 1800.00, "RENT_AND_UTILITIES"),
    ("RBC Visa Payment", 500.00, "LOAN_PAYMENTS"),
    ("OSAP Payment", 250.00, "LOAN_PAYMENTS"),
    ("TD Credit Card", 300.00, "LOAN_PAYMENTS"),
    ("Student Loan", 200.00, "LOAN_PAYMENTS"),
]